# Create numpy array

In [1]:
import numpy as np


nums = [[1,2,3],[4,5,6]]

nums = np.array(nums)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.__version__

'1.18.5'

In [3]:
#Dimension check

nums.ndim

2

In [4]:
#Create an array with 5 dimensions and varify  that it has 5 dimensions


import numpy as np

arr = np.array([1], ndmin = 4)

print(arr)

print('number of dimension :', arr.ndim)




[[[[1]]]]
number of dimension : 4


In [5]:
#if you want to find the shape of a matrix so u can use shape method

arr.shape

(1, 1, 1, 1)

In [6]:
#Zeroes array

arr = np.zeros(5)

arr

array([0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#Ones array

arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#Eye method

arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
#Diag array

arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
#Random number randint array

arr = np.random.randint(1,15,4)
arr

array([ 2, 13,  5,  7])

In [12]:
arr = np.random.rand(4)

arr

array([0.76842108, 0.82568118, 0.35367156, 0.56967815])

# Reshaping of data

In [13]:
import numpy as np

arr = np.random.randint(1,100,20)

arr

array([35, 19, 49, 54,  7, 23, 46, 22, 87, 28, 38, 27, 54,  8,  1, 50, 55,
       71, 21, 82])

In [14]:
arr1 = arr.reshape(2,10)

arr1

array([[35, 19, 49, 54,  7, 23, 46, 22, 87, 28],
       [38, 27, 54,  8,  1, 50, 55, 71, 21, 82]])

In [15]:
arr1.ndim

2

In [16]:
#Same random number generate  for using seed function

np.random.seed(123)

arr = np.random.randint(1,111,20)

arr2 = arr.reshape(5,4)

arr2

array([[110,  67,  93,  99],
       [103,  18,  84, 107],
       [ 58,  87,  98,  97],
       [ 48,  74,  33,  47],
       [ 97,  26,  84,  79]])

# Indexing and slicing 1D array

In [17]:
arr = np.array([1,3,5,7,9,32,76])

arr

array([ 1,  3,  5,  7,  9, 32, 76])

In [18]:
arr[5]

32

In [19]:
arr[-2]

32

In [20]:
arr[2:]    #Slicing

array([ 5,  7,  9, 32, 76])

In [21]:
arr[3:6]

array([ 7,  9, 32])

In [22]:
arr[2:7:2]

array([ 5,  9, 76])

# Indexing and Slicing 2D array

In [23]:
#Create 2D array


matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
matrix.shape

(3, 3)

In [25]:
matrix.ndim

2

In [26]:
#Indexing using double bracket notation

matrix[0][1]

10

In [27]:
matrix[1][1]

25

In [28]:
# Indexing using single bracket notation

matrix


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
matrix[0,1]

10

In [30]:
matrix[2,1]

40

In [31]:
matrix


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
matrix[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [33]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [34]:
np.random.seed(123)

matrix2 = np.random.randint(1,101,25).reshape(5,5)

matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [35]:
matrix2[1:3,1:4]

array([[87, 98, 97],
       [33, 47, 97]])

In [36]:
matrix2[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

# Conditional selection

In [37]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr>5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [40]:
arr[arr % 2 == 0] = 0

arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [41]:
#to find the minimum number index


import numpy as np


ar = np.array([3,4,7,4,2,676,8,4,2])

np.argmin(ar)

4

In [42]:
#to find the maximum number index

np.argmax(ar)

5

In [43]:
#to find the sqrt 

np.sqrt(ar)

array([ 1.73205081,  2.        ,  2.64575131,  2.        ,  1.41421356,
       26.        ,  2.82842712,  2.        ,  1.41421356])

In [44]:
np.exp(ar)

array([2.00855369e+001, 5.45981500e+001, 1.09663316e+003, 5.45981500e+001,
       7.38905610e+000, 3.82886247e+293, 2.98095799e+003, 5.45981500e+001,
       7.38905610e+000])

In [45]:
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

# Excercise


In [46]:
#create an array using array function

arr3 = np.array([1,3,6,8,4,9])

arr3

array([1, 3, 6, 8, 4, 9])

In [47]:
#create an array containing numbers from 20 to 40

arr3_new = np.arange(20,41)

arr3_new

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [48]:
#Create an array which contain  10 elements  and every element  is 5

fives = np.ones(10)*5


fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [49]:
#Create a 1-d array  and  then  convert it into 3-d array

arr4 = np.random.randint(1,50,24).reshape(3,4,2)

arr4

array([[[21, 40],
        [ 3, 21],
        [48, 49],
        [ 8, 42]],

       [[36, 29],
        [39, 34],
        [22, 31],
        [28, 35]],

       [[34, 13],
        [41,  4],
        [43,  6],
        [ 1, 12]]])

In [50]:
arr4.ndim

3

In [51]:
#Create 2-d array which contains random 25 numbers btw 0 and 1

arr5 = np.random.rand(5,5)

arr5

array([[0.43086276, 0.4936851 , 0.42583029, 0.31226122, 0.42635131],
       [0.89338916, 0.94416002, 0.50183668, 0.62395295, 0.1156184 ],
       [0.31728548, 0.41482621, 0.86630916, 0.25045537, 0.48303426],
       [0.98555979, 0.51948512, 0.61289453, 0.12062867, 0.8263408 ],
       [0.60306013, 0.54506801, 0.34276383, 0.30412079, 0.41702221]])

In [52]:
#Create array containing 20 random integer then replace even number with -1

np.random.seed(123
              )

arr6 = np.random.randint(1,50,20)



arr6[arr6 % 2 == 0] = -1


arr6

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

In [56]:
a = np.array([[1,2,3],[4,5,6]])

a.sum(axis = 0)

array([5, 7, 9])

In [58]:
a.sum(axis = 1)

array([ 6, 15])

In [68]:
b = np.array([[7,2,8],[9,2,7]])  #Note - we cant find dot matrix if the dimension is same, so we need to tanspose any array

np.dot(a,b.transpose())

array([[35, 34],
       [86, 88]])

In [69]:
np.cross(a,b)

array([[ 10,  13, -12],
       [ 23,  26, -37]])

In [84]:
#SORTING

np.random.seed(123)
c = np.random.randint(1,50,25).reshape(5,5)

c

array([[46,  3, 29, 35, 39],
       [18, 20, 43, 23, 34],
       [33, 48, 10, 33, 47],
       [33, 48, 26, 20, 15],
       [37, 33, 17,  5,  4]])

In [92]:
np.sort(c, axis = 1)  #row order

array([[ 3, 29, 35, 39, 46],
       [18, 20, 23, 34, 43],
       [10, 33, 33, 47, 48],
       [15, 20, 26, 33, 48],
       [ 4,  5, 17, 33, 37]])