# --------->NUMPY<--------


In [1]:
import numpy as np

my_list1 = [1,2,4,5,]

my_array1 = np.array(my_list1)
my_array1

array([1, 2, 4, 5])

In [2]:
my_list2 = [11,22,34,55]

my_list = [my_list1,my_list2]

my_array2 = np.array(my_list)
my_array2

array([[ 1,  2,  4,  5],
       [11, 22, 34, 55]])

In [3]:
my_array2.shape

(2, 4)

In [4]:
my_array2.dtype

dtype('int32')

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [9]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
np.diag(arr)   #if u need to find the diagonal so you have have to use this function

array([1, 2, 3, 4])

In [11]:
rand_no = np.random.randint(1,15,4)
rand_no

array([ 5, 11, 14,  3])

In [12]:
np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.69119330e-306, 1.02360867e-306,
        1.60220528e-306, 1.78019082e-306, 6.89805151e-307],
       [1.78020169e-306, 8.45559303e-307, 8.06612616e-308,
        6.89810244e-307, 1.22387550e-307, 2.22522596e-306]])

In [13]:
my_array1*my_array1 

array([ 1,  4, 16, 25])

# RESHAPING


In [14]:
arr = np.random.randint(1,100,20)
arr = arr.reshape(2,10)
arr

array([[98,  7, 50, 16,  9, 95, 32, 74, 68, 35],
       [72, 81, 43, 23, 30,  7, 67, 58,  3,  7]])

In [15]:
arr.ndim

2

In [16]:
arr1 = np.random.randint(1,100,50)    #3D array
arr1 = arr1.reshape(2,5,5)
arr1

array([[[15, 52, 58, 26, 59],
        [90, 35, 70, 76, 20],
        [45, 72, 62, 98, 21],
        [17, 78, 73, 67, 70],
        [63,  9, 97, 76, 96]],

       [[46,  2, 55, 19, 86],
        [59, 19, 98, 81, 30],
        [31, 32,  9, 14, 98],
        [78, 65, 74, 94, 23],
        [72, 89, 70,  2, 19]]])

In [17]:
arr1.ndim

3

If you want to generate a same random no:

In [71]:
np.random.seed(123)
arr = np.random.randint(1,100,10)
arr

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

# SLICING

In [18]:
array2 = np.array([2,3,5,78,8])
array2

array([ 2,  3,  5, 78,  8])

In [19]:
arr = array2[2:4]
arr

array([ 5, 78])

In [20]:
arr[0] = 9
array2

array([ 2,  3,  9, 78,  8])

In [21]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2[0:4] = 10
arr2

array([10, 10, 10, 10,  5,  6,  7,  8,  9])

In [23]:
arr3 = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,14,15,16]))
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 14, 15, 16]])

In [24]:
arr3[1][1:3]  #1D slicing

array([7, 8])

In [25]:
arr3[1:,2:4]

array([[ 8,  9],
       [14, 15]])

In [26]:
arr3[:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [27]:
np.random.seed(123)
matrix = np.random.randint(1,101,25).reshape(5,5)
matrix

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [28]:
matrix[2:4,1:3]


array([[33, 47],
       [79, 37]])

In [29]:
matrix[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

In [30]:
arr_lenght = matrix.shape[1]
arr_lenght

5

In [31]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
mask = arr > 5
arr[mask]

array([ 6,  7,  8,  9, 10])

In [33]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [35]:
arr[arr == 5]

array([5])

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.random.seed(123)
matrix1 = np.random.randint(1,12,9).reshape(3,3)
matrix2 = np.random.randint(5,15,9).reshape(3,3)
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [38]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [39]:
matrix1 + matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [40]:
matrix1 * matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [41]:
matrix1 / matrix2

array([[0.6       , 0.5       , 0.5       ],
       [0.4       , 0.8       , 0.78571429],
       [1.25      , 0.77777778, 0.4       ]])

In [42]:
matrix1 / 1

array([[ 3.,  3.,  7.],
       [ 2.,  4., 11.],
       [10.,  7.,  2.]])

In [43]:
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

# some more numpy function

In [44]:
arr = np.array([2,80,1,97,5])

#if u want to find the min number 

np.min(arr)

1

In [45]:
np.max(arr)

97

In [46]:
np.argmin(arr) #if u want to find the min number index than u will use np.argmin()

2

In [47]:
np.argmax(arr)

3

In [48]:
np.sqrt(arr) #if u want to find the square root of any array

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [49]:
np.linspace(1,15,50)  #if u wants between of any number so u can use linspace

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [50]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [51]:
#rows = 1 , columns = 0

np.min(matrix1,axis=1)

array([3, 2, 2])

In [52]:
np.max(matrix1,axis=0)

array([10,  7, 11])

In [53]:
np.sum(matrix1,axis=1)

array([13, 17, 19])

In [54]:
np.prod(matrix1,axis=0)

array([ 60,  84, 154])

Create an array containing number  from 20 to 40

In [55]:
np.arange(20,41)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

Create an array which contain 10 element and every element is 5

In [56]:
np.ones(10)* 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create  a 1-d array and then convert it into 3-d array

In [57]:
np.random.randint(1,50,24).reshape(3,4,2)

array([[[17,  5],
        [ 4,  3],
        [21, 40],
        [ 3, 21]],

       [[48, 49],
        [ 8, 42],
        [36, 29],
        [39, 34]],

       [[22, 31],
        [28, 35],
        [34, 13],
        [41,  4]]])

Create 2-D array which contains random 25 number between 0 and 1 

In [58]:
np.random.rand(4,5)

array([[0.09210494, 0.43370117, 0.43086276, 0.4936851 , 0.42583029],
       [0.31226122, 0.42635131, 0.89338916, 0.94416002, 0.50183668],
       [0.62395295, 0.1156184 , 0.31728548, 0.41482621, 0.86630916],
       [0.25045537, 0.48303426, 0.98555979, 0.51948512, 0.61289453]])

# Create array containing 20 random integer then replace every even number with -1

In [59]:
even_number = np.random.randint(1,50,20)
even_number[even_number % 2 == 0] = -1
even_number

array([13, 19, -1, -1, 45, -1, 49, -1, 23, -1, -1, -1, -1, -1, -1, -1, 35,
       -1, -1, -1])

In [60]:
new_mat = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
new_mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
new_mat[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

# Concatenate  two 1-d array

In [62]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])
np.hstack((ar1,ar2))  #Horizontal join 


array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
np.vstack((ar1,ar2))  #Vertical join

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [1]:
%timeit 2 + 5


18.4 ns ± 1.31 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [2]:
%timeit [i**2 for i in range(1,4)]

2.42 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


%%timeit
l = []
for i in range(1,4):
    l.append(i)